[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
lib_deps =
    askuric/Simple FOC @ ^2.4.0
    SPI
    Wire
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D SIMPLEFOC_STM32_DEBUG
    -Wl,-u,_printf_float
    -D F_CPU=96000000L
